name: Python Package (Conda)

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.10
        auto-activate-base: false
        activate-environment: test-env
        environment-file: environment.yml
        condarc-file: |
          channels:
            - defaults

    - name: Verify Conda environment
      run: conda info --envs

    - name: Install additional dependencies (if needed)
      run: |
        conda install flake8 pytest -y

    - name: Lint with flake8
      run: |
        # Stop the build on syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Continue build but show warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: pytest
